$engine: 3
$onesync: on
name: ESX Overextended
version: 0.0.0
author: ESX Overextended
description: The recipe of ESX-Overextended FiveM RP framework, containing Jobs, Housing, Vehicles & more!

tasks:
  # Download and prepare server.cfg / loadingscreen / database
  - action: download_github
    src: https://github.com/esx-overextended/txAdminRecipe
    ref: main
    dest: ./tmp/txAdminRecipe

  - action: move_path
    src: ./tmp/txAdminRecipe/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/txAdminRecipe/es_extended.cfg
    dest: ./es_extended.cfg

  - action: move_path
    src: ./tmp/txAdminRecipe/illenium_appearance.cfg
    dest: ./illenium_appearance.cfg

  - action: move_path
    src: ./tmp/txAdminRecipe/ox_inventory.cfg
    dest: ./ox_inventory.cfg

  - action: move_path
    src: ./tmp/txAdminRecipe/ox_lib.cfg
    dest: ./ox_lib.cfg

  - action: move_path
    src: ./tmp/txAdminRecipe/ox_target.cfg
    dest: ./ox_target.cfg

  - action: move_path
    src: ./tmp/txAdminRecipe/pma_voice.cfg
    dest: ./pma_voice.cfg

  - action: move_path
    src: ./tmp/txAdminRecipe/logo.png
    dest: ./logo.png

  - action: connect_database

  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]

  # Download standalone resources
  - action: download_file
    path: ./tmp/oxmysql.zip
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
  - action: unzip
    src: ./tmp/oxmysql.zip
    dest: ./resources/[standalone]

  - action: download_file
    path: ./tmp/ox_lib.zip
    url: https://github.com/overextended/ox_lib/releases/latest/download/ox_lib.zip
  - action: unzip
    src: ./tmp/ox_lib.zip
    dest: ./resources/[ox]

  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: main
    dest: ./resources/[standalone]/pma-voice

  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: master
    dest: ./resources/[standalone]/bob74_ipl

  - action: download_github
    src: https://github.com/citizenfx/screenshot-basic
    ref: master
    dest: ./resources/[standalone]/screenshot-basic

  # Download core resources and ESX dependencies
  - action: download_github
    src: https://github.com/esx-overextended/cron # Must remove this in-favor of ox_lib's cron & adjust dependant resources...
    ref: main
    dest: ./resources/[core]/cron

  - action: download_github
    src: https://github.com/esx-overextended/es_extended
    ref: main
    dest: ./resources/[core]/es_extended
  - action: query_database
    file: ./resources/[core]/es_extended/esx-overextended.sql

  - action: download_github
    src: https://github.com/esx-overextended/esx_identity
    ref: main
    dest: ./resources/[core]/esx_identity
  - action: query_database
    file: ./resources/[core]/esx_identity/esx_identity.sql

  - action: download_github
    src: https://github.com/esx-overextended/esx_multicharacter
    ref: main
    dest: ./resources/[core]/esx_multicharacter
  - action: query_database
    file: ./resources/[core]/esx_multicharacter/esx_multicharacter.sql

  - action: download_github
    src: https://github.com/esx-overextended/esx_menu_list
    ref: main
    dest: ./resources/[core]/esx_menu_list

  - action: download_file
    path: ./tmp/illenium-appearance.zip
    url: https://github.com/iLLeniumStudios/illenium-appearance/releases/latest/download/illenium-appearance.zip
  - action: unzip
    src: ./tmp/illenium-appearance.zip
    dest: ./resources/[core]
  - action: write_file
    file: ./resources/[core]/illenium-appearance/fxmanifest.lua
    append: true
    data: |
      provides { "esx_skin", "skinchanger" }
  - action: query_database
    file: ./resources/[core]/illenium-appearance/sql/player_outfits.sql
  - action: query_database
    file: ./resources/[core]/illenium-appearance/sql/player_outfit_codes.sql

  - action: download_github
    src: https://github.com/esx-overextended/esx_loadingscreen
    ref: main
    dest: ./resources/[core]/esx_loadingscreen

  - action: download_file
    path: ./tmp/ox_inventory.zip
    url: https://github.com/overextended/ox_inventory/releases/latest/download/ox_inventory.zip
  - action: unzip
    src: ./tmp/ox_inventory.zip
    dest: ./resources/[ox]

  - action: download_github
    src: https://github.com/overextended/ox_fuel
    ref: main
    dest: ./resources/[ox]/ox_fuel

  - action: replace_string
    file: ./resources/[ox]/ox_fuel/config.lua
    search: 'ox_target = false'
    replace: 'ox_target = true'

  - action: download_github
    src: https://github.com/overextended/ox_target
    ref: main
    dest: ./resources/[ox]/ox_target

  - action: move_path
    src: ./tmp/txAdminRecipe/ox_target_esx.lua
    dest: ./resources/[ox]/ox_target/client/framework/esx.lua
    overwrite: true

  - action: download_file
    path: ./tmp/ox_doorlock.zip
    url: https://github.com/overextended/ox_doorlock/releases/latest/download/ox_doorlock.zip
  - action: unzip
    src: ./tmp/ox_doorlock.zip
    dest: ./resources/[ox]

  # Prevent GitHub Throttling
  - action: waste_time
    seconds: 5

  - action: download_github
    src: https://github.com/esx-framework/esx_addonaccount
    ref: main
    dest: ./resources/[addons]/esx_addonaccount
  - action: query_database
    file: ./resources/[addons]/esx_addonaccount/esx_addonaccount.sql

  - action: download_github
    src: https://github.com/esx-framework/esx_addoninventory
    ref: main
    dest: ./resources/[addons]/esx_addoninventory
  - action: query_database
    file: ./resources/[addons]/esx_addoninventory/esx_addoninventory.sql

  - action: download_github
    src: https://github.com/esx-framework/esx_datastore
    ref: main
    dest: ./resources/[addons]/esx_datastore
  - action: query_database
    file: ./resources/[addons]/esx_datastore/esx_datastore.sql

  - action: download_github
    src: https://github.com/esx-framework/esx_license
    ref: main
    dest: ./resources/[addons]/esx_license
  - action: query_database
    file: ./resources/[addons]/esx_license/esx_license.sql

  - action: download_github
    src: https://github.com/esx-framework/esx_billing
    ref: main
    dest: ./resources/[addons]/esx_billing
  - action: query_database
    file: ./resources/[addons]/esx_billing/esx_billing.sql

  - action: download_github
    src: https://github.com/esx-framework/esx_society
    ref: main
    dest: ./resources/[addons]/esx_society
  - action: query_database
    file: ./resources/[addons]/esx_society/esx_society.sql

  - action: download_github
    src: https://github.com/esx-framework/esx_jobs
    ref: main
    dest: ./resources/[addons]/esx_jobs
  - action: query_database
    file: ./resources/[addons]/esx_jobs/esx_jobs.sql

  - action: download_github
    src: https://github.com/esx-framework/esx_joblisting
    ref: main
    dest: ./resources/[addons]/esx_joblisting
  - action: query_database
    file: ./resources/[addons]/esx_joblisting/esx_joblisting.sql

  - action: download_github
    src: https://github.com/esx-framework/esx_status
    ref: main
    dest: ./resources/[addons]/esx_status
  - action: query_database
    file: ./resources/[addons]/esx_status/esx_status.sql

  - action: download_github
    src: https://github.com/esx-framework/esx_basicneeds
    ref: main
    dest: ./resources/[addons]/esx_basicneeds
  - action: query_database
    file: ./resources/[addons]/esx_basicneeds/esx_basicneeds.sql

  - action: download_github
    src: https://github.com/esx-framework/esx_optionalneeds
    ref: main
    dest: ./resources/[addons]/esx_optionalneeds
  - action: query_database
    file: ./resources/[addons]/esx_optionalneeds/esx_optionalneeds.sql

  # Prevent GitHub Throttling
  - action: waste_time
    seconds: 5

  - action: download_github
    src: https://github.com/esx-overextended/esx_vehicleshop
    ref: main
    dest: ./resources/[addons]/esx_vehicleshop
  - action: query_database
    file: ./resources/[addons]/esx_vehicleshop/esx_vehicleshop.sql

  - action: download_github
    src: https://github.com/esx-overextended/esx_garage
    ref: main
    dest: ./resources/[addons]/esx_garage

  - action: download_github
    src: https://github.com/esx-framework/esx_boat
    ref: main
    dest: ./resources/[addons]/esx_boat
  - action: query_database
    file: ./resources/[addons]/esx_boat/esx_boat.sql

  - action: download_github
    src: https://github.com/esx-framework/esx_property
    ref: main
    dest: ./resources/[addons]/esx_property

  - action: download_github
    src: https://github.com/esx-framework/esx_dmvschool
    ref: main
    dest: ./resources/[addons]/esx_dmvschool
  - action: query_database
    file: ./resources/[addons]/esx_dmvschool/esx_dmvschool.sql

  - action: download_github
    src: https://github.com/esx-framework/esx_drugs
    ref: main
    dest: ./resources/[addons]/esx_drugs
  - action: query_database
    file: ./resources/[addons]/esx_drugs/esx_drugs.sql

  - action: download_github
    src: https://github.com/esx-framework/esx_banking
    ref: main
    dest: ./resources/[addons]/esx_banking
  - action: query_database
    file: ./resources/[addons]/esx_banking/banking.sql

  - action: download_github
    src: https://github.com/esx-framework/esx_lscustom
    ref: main
    dest: ./resources/[addons]/esx_lscustom

  # Prevent GitHub Throttling
  - action: waste_time
    seconds: 5

  - action: download_github
    src: https://github.com/esx-framework/esx_policejob
    ref: main
    dest: ./resources/[addons]/esx_policejob
  - action: query_database
    file: ./resources/[addons]/esx_policejob/esx_policejob.sql

  - action: download_github
    src: https://github.com/esx-framework/esx_taxijob
    ref: main
    dest: ./resources/[addons]/esx_taxijob
  - action: query_database
    file: ./resources/[addons]/esx_taxijob/esx_taxijob.sql

  - action: download_github
    src: https://github.com/esx-framework/esx_ambulancejob
    ref: main
    dest: ./resources/[addons]/esx_ambulancejob
  - action: query_database
    file: ./resources/[addons]/esx_ambulancejob/esx_ambulancejob.sql

  - action: download_github
    src: https://github.com/esx-framework/esx_mechanicjob
    ref: main
    dest: ./resources/[addons]/esx_mechanicjob
  - action: query_database
    file: ./resources/[addons]/esx_mechanicjob/esx_mechanicjob.sql

  - action: download_github
    src: https://github.com/acscripts/ac_radio
    ref: main
    dest: ./resources/[standalone]/ac_radio

  - action: download_github
    src: https://github.com/Concept-Collective/cc-chat
    ref: main
    dest: ./resources/[standalone]/cc-chat

  - action: download_github
    src: https://github.com/Concept-Collective/cc-rpchat
    ref: main
    dest: ./resources/[standalone]/cc-rpchat

  - action: download_github
    src: https://github.com/XProject/x-config
    ref: master
    dest: ./resources/[project-x]/x-config

  - action: download_github
    src: https://github.com/XProject/x-weathertime
    ref: main
    dest: ./resources/[project-x]/x-weathertime

  - action: download_github
    src: https://github.com/XProject/x-radiolist
    ref: master
    dest: ./resources/[project-x]/x-radiolist

  - action: download_github
    src: https://github.com/XProject/x-visual
    ref: master
    dest: ./resources/[project-x]/x-visual

  # Prevent GitHub Throttling
  - action: waste_time
    seconds: 5

  # Maps
  - action: download_github
    src: https://github.com/esx-overextended/patoche_pdm_cardealer
    ref: main
    dest: ./resources/[maps]/patoche_pdm_cardealer

  ## Cleanup
  - action: remove_path
    path: ./tmp
